cors:
  originPatterns: http://localhost:8080
spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/api_restful_course_db?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
        # properties:
        # hibernate:
      # dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  springdoc:
    swagger-ui:
      path: /docs-restful-api-aws.html
    api-docs:
      path: /docs-restful-api-aws.html
    packagesToScan: com.example.api.controllers